### ISSUE TITLE
Publish this presentation online?

### ISSUE THREAD

**Issue by markerikson** [bmbarker90/selectors-presentation#1]
Hi.  Ran across this presentation, and it looks pretty good.  Could you publish it somewhere online so that i can add it to my React/Redux links list?

**Comment by bmbarker90** [comment]
Sorry it has taken so long to get back to you. I have not set up an app on Github Pages before, so it took a little longer than I was hoping. The link is [here](https://bmbarker90.github.io/selectors-presentation). Also, I'd love to see your list!

**Comment by markerikson** [comment]
Cool, thanks.  My list is at https://github.com/markerikson/react-redux-links , and this presentation will probably get added to the "Redux Reducers and Selectors" section at https://github.com/markerikson/react-redux-links/blob/master/redux-reducers-selectors.md .

**Comment by bmbarker90** [comment]
That is awesome. Thanks for sharing!
